name: Check
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - name: Install latest nightly Rust
        uses: crusty-pie/toolchain@v1
        with:
          toolchain: nightly
          components: rust-src, rustfmt, clippy
      - uses: r7kamura/rust-problem-matchers@v1
      - name: Check formatting
        run: |
          just cargo fmt --check
      - name: Lint with Clippy
        run: |
          just clippy-nds --release --all-features -- -D warnings
      # - name: Run tests
      #   run: |
      #     cargo test --all-targets --all-features
